spring:
  application:
    name: eureka-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false  # 禁用 Ribbon 负载均衡
server:
  port: 8091
eureka:
  instance:
    hostname: localhost  # 实例的主机名
    preferIpAddress: true
  client:
    # Eureka服务端不需要向Eureka服务注册
    register-with-eureka: true  # 注意属性名的正确拼写
    # 不在本地缓存注册信息
    fetch-registry: true  # 注意属性名的正确拼写
    # enabled: true
  service-url:
    defaultZone: http://localhost:8090/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5  # 同步注册表时的等待时间
    enable-self-preservation: false